name: ChurchApp
options:
  bundleIdPrefix: org.sjca
  developmentLanguage: en
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    ENABLE_PREVIEWS: "YES"
  configs:
    Debug:
      ENABLE_TESTABILITY: YES
      ONLY_ACTIVE_ARCH: YES
targets:
  ChurchApp:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
    info:
      path: Generated/Info.plist
      properties:
        CFBundleDisplayName: "拾穗 | Gleaning"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        UILaunchScreen: {}
        UIBackgroundModes:
          - audio
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        ITSAppUsesNonExemptEncryption: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.sjca.app
        PRODUCT_NAME: "SJCA"
        MARKETING_VERSION: "1.3"
        CURRENT_PROJECT_VERSION: "6"
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SUPPORTS_MACCATALYST: "NO"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: MS583APS4H
    schemes: {}
  ChurchAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_NAME: ChurchAppTests
        PRODUCT_BUNDLE_IDENTIFIER: org.sjca.app.tests
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SJCA.app/SJCA"
        DEVELOPMENT_TEAM: MS583APS4H
    dependencies:
      - target: ChurchApp
schemes:
  ChurchApp:
    build:
      targets:
        ChurchApp: all
        ChurchAppTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ChurchAppTests
    archive:
      config: Release
